name: Run Tests on PR to libre-capital/assessment

on:
  pull_request:
    branches:
      - libre-capital/assessment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test
